baseURL = "https://brendanmccoy.net"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Docdock"
theme = "docdock"

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]